import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { IsEmail, MinLength } from "class-validator";
import { Field, ID, InputType, ObjectType } from "type-graphql";
import { mapper } from "../dynamodb";
import { IsUnique } from "../validations/IsUnique";

@table("graphql-data")
@ObjectType()
export class User {
  @autoGeneratedHashKey()
  @Field(() => ID)
  id!: string;

  @attribute()
  @Field()
  email!: string;

  @attribute()
  @Field()
  firstName: string;

  @attribute()
  @Field()
  lastName: string;

  @attribute()
  @Field()
  password!: string;
}

@InputType()
export class SignUpInput {
  @Field()
  @IsEmail()
  @IsUnique(User)
  email!: string;

  @Field()
  @MinLength(6)
  password!: string;
}

(() => {
  mapper.ensureTableExists(User, {
    readCapacityUnits: 5,
    writeCapacityUnits: 5,
  });
})();
