import { Field, ID, InputType, ObjectType } from "type-graphql";
import {
  attribute,
  autoGeneratedHashKey,
  table,
} from "@aws/dynamodb-data-mapper-annotations";
import { mapper } from "../dynamodb";
import _ from "lodash";
import { Length } from "class-validator";

@table("Workspaces")
@ObjectType()
export class Workspace {
  @autoGeneratedHashKey()
  @Field((_) => ID)
  id!: string;

  @attribute()
  @Field()
  name!: string;

  @attribute()
  @Field()
  slug!: string;
}

@InputType()
export class NewWorkspaceInput {
  @Field()
  name: string;

  @Field()
  @Length(3, 64)
  slug: string;
}

(() => {
  mapper.ensureTableExists(Workspace, {
    readCapacityUnits: 5,
    writeCapacityUnits: 5,
  });
})();
